### ISSUE TITLE
mingw-w64-x86_64-libepoxy-1.5.10-4 missing header regression due to removed dep on angleproject

### ISSUE THREAD

**Issue by berrange** [msys2/MINGW-packages#16492]
### Description / Steps to reproduce the issue

With the update to mingw-w64-x86_64-libepoxy-1.5.10-4 QEMU CI jobs no longer able to compile with libepoxy

https://gitlab.com/qemu-project/qemu/-/jobs/4015682307

```
FAILED: libcommon.fa.p/ui_egl-helpers.c.obj 
"cc" "-m64" "-mcx16" "-Ilibcommon.fa.p" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/capstone" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/pixman-1" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/libpng16" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/spice-server" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/spice-1" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/glib-2.0" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/lib/glib-2.0/include" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/p11-kit-1" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/SDL2" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/ncursesw" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/gtk-3.0" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/pango-1.0" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/harfbuzz" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/freetype2" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/fribidi" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/cairo" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/gdk-pixbuf-2.0" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/webp" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/atk-1.0" "-IC:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/libusb-1.0" "-fdiagnostics-color=auto" "-Wall" "-Winvalid-pch" "-Werror" "-std=gnu11" "-O2" "-g" "-iquote" "." "-iquote" "C:/GitLab-Runner/builds/qemu-project/qemu" "-iquote" "C:/GitLab-Runner/builds/qemu-project/qemu/include" "-iquote" "C:/GitLab-Runner/builds/qemu-project/qemu/tcg/i386" "-U_FORTIFY_SOURCE" "-D_FORTIFY_SOURCE=2" "-fno-pie" "-no-pie" "-D_GNU_SOURCE" "-D_FILE_OFFSET_BITS=64" "-D_LARGEFILE_SOURCE" "-fno-strict-aliasing" "-fno-common" "-fwrapv" "-Wundef" "-Wwrite-strings" "-Wmissing-prototypes" "-Wstrict-prototypes" "-Wredundant-decls" "-Wold-style-declaration" "-Wold-style-definition" "-Wtype-limits" "-Wformat-security" "-Wformat-y2k" "-Winit-self" "-Wignored-qualifiers" "-Wempty-body" "-Wnested-externs" "-Wendif-labels" "-Wexpansion-to-defined" "-Wimplicit-fallthrough=2" "-Wmissing-format-attribute" "-Wno-missing-include-dirs" "-Wno-shift-negative-value" "-Wno-psabi" "-fstack-protector-strong" "-DHWY_SHARED_DEFINE" "-DLIBDEFLATE_DLL" "-D_POSIX_C_SOURCE=199506L" "-DNCURSES_WIDECHAR" "-DNCURSES_WIDECHAR=1" "-Dmain=SDL_main" "-Wno-undef" "-DSTRUCT_IOVEC_DEFINED" -MD -MQ libcommon.fa.p/ui_egl-helpers.c.obj -MF "libcommon.fa.p/ui_egl-helpers.c.obj.d" -o libcommon.fa.p/ui_egl-helpers.c.obj "-c" ../ui/egl-helpers.c
In file included from C:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/epoxy/egl.h:46,
                 from C:/GitLab-Runner/builds/qemu-project/qemu/include/ui/egl-helpers.h:5,
                 from ../ui/egl-helpers.c:21:
C:/GitLab-Runner/builds/qemu-project/qemu/msys64/mingw64/include/epoxy/egl_generated.h:11:10: fatal error: EGL/eglplatform.h: No such file or directory
   11 | #include "EGL/eglplatform.h"
      |          ^~~~~~~~~~~~~~~~~~~
```

Our most recent previous working job was

https://gitlab.com/qemu-project/qemu/-/jobs/3997737483

which had mingw-w64-i686-libepoxy-1.5.10-3

Given the missing "EGL/eglplatform.h" header, it looks liked the  mingw-w64-i686-libepoxy-1.5.10-4 package is missing a dependency against the package that is supposed to provide this header.  I believe the missing package is mingw-w64-i686-angleproject. There used to be pulled in as a dep in our previous working jobs, but is now missing.

This regression appears to be caused by https://github.com/msys2/MINGW-packages/commit/2b5c48a6dcd5b17601d836ada803578a99573fb8  which removed the depends on angleproject

### Expected behavior

Be able to successfully compile code that uses the /msys64/mingw64/include/epoxy/egl_generated.h header

### Actual behavior

Unable to successfully compile code that uses the /msys64/mingw64/include/epoxy/egl_generated.h header due to it #include'ing EGL/eglplatform.h which does not exist.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

windows/amd64   (GitLab Windows shared runners)

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
@lb90 Would you like to look into this issue please?

**Comment by lb90** [comment]
Yep, I'm preparing a PR

**Comment by lb90** [comment]
Opened https://github.com/msys2/MINGW-packages/pull/16493

**Comment by lazka** [comment]
should be fixed now

**Comment by lazka** [comment]
hm, so angle depends on patched versions of egl headers? https://github.com/google/angle/search?q=eglext_angle.h

**Comment by lb90** [comment]
Hi! First of all, sorry too for the breakage too, @kasper93!

> We could also include eglext_angle.h explicitly, which is apparently installed, but not included by eglext.h. And it does work https://github.com/kasper93/mpv/actions/runs/4564075388. The question is what is the gain of splitting those headers and possibly having incompatibilities between vanilla EGL vs ANGLE?

The end goal is to enable EGL/GLES also via Mesa Gallium d3d12 as an alternative to ANGLE, so sers may choose between either angle or mesa for a GLES implementation. Well, technically EGL also supports OpenVG, for which several implementations exist, so IMO making angle provide the EGL headers is not quite a great solution. After all the headers are developed independently by Khronos. Of course, if other disagree then we can change egl-headers and make it provide upstream ANGLE headers, no problem with that! 🙂

Another thing is that angleproject development is not quite active nowdays, and updating our angleproject package is not quite easy.

Another option is to distribute the two ANGLE-specific headers `EGL/eglext_angle.h`, `GLES2/gl2ext_angle.h` from `egl-headers`, `gles-headers` respectively, and patch `EGL/eglext.h` to include `eglext_angle.h`.

> Looking at all the code (including samples) at google/angle, they never include it directly, but indirectly through eglext.h
[eglext_angle.h](https://github.com/search?q=repo%3Agoogle%2Fangle+eglext_angle.h&type=code) vs [EGL/eglext.h](https://github.com/search?q=repo%3Agoogle%2Fangle%20EGL%2Feglext.h&type=code)

Yeah, to me this looks somewhat of a a shortcut (from a time where on Windows you anly had ANGLE, or where project-specific build environments had to choose one GLES library anyway). EGL/glext is an official Khronos header: https://registry.khronos.org/EGL/ which contains approved extensions (indeed a few ANGLE extensions are contained in it). Implementation-specific extensions that are not upstreamed should go in a specific header instead.

Sorry for the boring discussion :smile: so, in the end, we can take any action, but for me the cleanest approach is to have have an include for `EGL/eglext_angle.h` if they use non upstreamed ANGLE extensions

**Comment by lb90** [comment]
Looks like the original issue is now fixed: https://gitlab.com/qemu-project/qemu/-/jobs/4066136799
