### ISSUE TITLE
Pycairo Fails to Build with Python 3.9

### ISSUE THREAD

**Issue by danyeaw** [msys2/MINGW-packages#9089]
It looks like pycairo is trying to build using the msys gcc, instead of mingw. When I run `pip install pycairo` I get the following error:
```
  Command ['/home/dan/gaphor/.venv39/bin/pip', 'install', '--no-deps', 'file:///home/dan/.cache/pypoetry/artifacts/2a/a4/aa/1e8cdf30d6e5388c9c41277f3b9f9be63f680a3ec28d12c8aecb49f3a7/pycairo-1.20.1.tar.gz'] errored with the following return code 1, and output:
  Processing /home/dan/.cache/pypoetry/artifacts/2a/a4/aa/1e8cdf30d6e5388c9c41277f3b9f9be63f680a3ec28d12c8aecb49f3a7/pycairo-1.20.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Building wheels for collected packages: pycairo
    Building wheel for pycairo (PEP 517): started
    Building wheel for pycairo (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/dan/gaphor/.venv39/bin/python3.9.exe /home/dan/gaphor/.venv39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp4q9rf99b
         cwd: /tmp/pip-req-build-zq8_awl8
    Complete output (11 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9
    creating build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo
    copying cairo/__init__.py -> build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo
    copying cairo/__init__.pyi -> build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo
    copying cairo/py.typed -> build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo
    running build_ext
    error: [Errno 2] No such file or directory: 'x86_64-pc-msys-gcc'
```

If I do install the msys gcc, then the build also fails with:
```
    building 'cairo._cairo' extension
    creating build/temp.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9
    creating build/temp.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo
    x86_64-pc-msys-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -march=x86-64 -mtune=generic -O2 -pipe -march=x86-64 -mtune=generic -O2 -pipe -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=20 -DPYCAIRO_VERSION_MICRO=1 -IC:/tools/msys64/mingw64/include/cairo -IC:/tools/msys64/mingw64/include/lzo -IC:/tools/msys64/mingw64/include -IC:/tools/msys64/mingw64/include/libpng16 -IC:/tools/msys64/mingw64/include/freetype2 -IC:/tools/msys64/mingw64/include/harfbuzz -IC:/tools/msys64/mingw64/include/glib-2.0 -IC:/tools/msys64/mingw64/lib/glib-2.0/include -IC:/tools/msys64/mingw64/include/pixman-1 -I/home/dan/gaphor/.venv39/include -I/usr/include/python3.9 -c cairo/bufferproxy.c -o build/temp.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo/bufferproxy.o -Wall -Warray-bounds -Wcast-align -Wconversion -Wextra -Wformat=2 -Wformat-nonliteral -Wformat-security -Wimplicit-function-declaration -Winit-self -Winline -Wmissing-format-attribute -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing -Wundef -Wunused-but-set-variable -Wswitch-default -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-command-line-argument -fno-strict-aliasing -fvisibility=hidden -std=c99
    In file included from cairo/bufferproxy.c:32:
    /usr/include/python3.9/Python.h:44:10: fatal error: crypt.h: No such file or directory
       44 | #include <crypt.h>
          |          ^~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/x86_64-pc-msys-gcc' failed with exit code 1
```
If someone could point me in the right direction on what is telling this build to use msys-gcc instead of mingw-gcc, I would be glad to submit a PR.

**Comment by lazka** [comment]
Does it happen with 3.8?

**Comment by danyeaw** [comment]
> Does it happen with 3.8?

Nope, works fine with 3.8

**Comment by lazka** [comment]
I also tested with pycairo at one point and it worked, so I suspect a venv issue.

**Comment by danyeaw** [comment]
I get the same error if I create a new virtualenv and only install pycairo:
```
dan@DESKTOP-5CFIFKJ MINGW64 ~/gaphor
$ rm -rf .venv39

dan@DESKTOP-5CFIFKJ MINGW64 ~/gaphor
$ python3.9 -m venv .venv39

dan@DESKTOP-5CFIFKJ MINGW64 ~/gaphor
$ source .venv39/bin/activate
(.venv39)
dan@DESKTOP-5CFIFKJ MINGW64 ~/gaphor
$ pip install pycairo
Collecting pycairo
  Downloading pycairo-1.20.1.tar.gz (344 kB)
     |████████████████████████████████| 344 kB 2.6 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: pycairo
  Building wheel for pycairo (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dan/gaphor/.venv39/bin/python3.9.exe /home/dan/gaphor/.venv39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpb9nkjlbe
       cwd: /tmp/pip-install-_cvu2aj4/pycairo_83ba6bdc1db24eaca5a710a3d4b97edc
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9
  creating build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo
  copying cairo/__init__.py -> build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo
  copying cairo/__init__.pyi -> build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo
  copying cairo/py.typed -> build/lib.mingw64_nt-10.0-21390-3.2.0-340.x86_64-x86_64-3.9/cairo
  running build_ext
  error: [Errno 2] No such file or directory: 'x86_64-pc-msys-gcc'
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
Failed to build pycairo
ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/home/dan/gaphor/.venv39/bin/python3.9.exe -m pip install --upgrade pip' command.
```

**Comment by lazka** [comment]
It works here:

```
$ python3.9 -m venv _venv
$ cd _venv/
$ source bin/activate
$ pip install --no-cache-dir pycairo
Collecting pycairo
  Downloading pycairo-1.20.1.tar.gz (344 kB)
     |################################| 344 kB 409 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: pycairo
  Building wheel for pycairo (PEP 517) ... done
  Created wheel for pycairo: filename=pycairo-1.20.1-cp39-cp39-mingw_x86_64_ucrt.whl size=82296 sha256=f638c4a0cfc6cb4f17201356e6bb773a06c8e47190b9bca0545c8966ccca3bc7
  Stored in directory: C:/Users/user/AppData/Local/Temp/pip-ephem-wheel-cache-m3n03dsp/wheels/29/a9/b9/15e3dc25ce0db1d40546014674ee0cac132f94bf3a9607d02b
Successfully built pycairo
Installing collected packages: pycairo
Successfully installed pycairo-1.20.1
(_venv)
```

Your output suggests that it's using msys python.

**Comment by danyeaw** [comment]
@lazka Yup, you were absolutely right, somehow I was using msys python, soon as I removed it everything is working great. Thanks for your help troubleshooting!
