### ISSUE TITLE
[mingw-w64-headers] `windows.foundation.h` breaks compile since #10033

### ISSUE THREAD

**Issue by past-due** [msys2/MINGW-packages#10120]
Since the update to `mingw-w64-headers` in #10033, including `windows.foundation.h` breaks compilation in at least `clang64`.

`example.cpp`:
```cpp
#include <windows.foundation.h>

int main() {
   return 0;
}
```
`x86_64-w64-mingw32-g++.exe --target=x86_64-windows-gnu -O3 -DNDEBUG -std=gnu++17 example.cpp -o example.exe`
Output:
```
In file included from example.cpp:1:
C:/msys64/clang64/x86_64-w64-mingw32/include/windows.foundation.h:75:26: error: ISO C++ forbids forward references to 'enum' types
            typedef enum PropertyType PropertyType;
                         ^
1 error generated.
```

This is caused by changes to `windows.foundation.h`: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/a2eb3ea3aaa7c780c4b4ab30d71169f442788864/tree//mingw-w64-headers/include/windows.foundation.h?diff=1ee3a1a6b0b1df2fd55f7d225711fd5601ac6513

**Comment by lazka** [comment]
@Biswa96 @lhmouse any ideas?

**Comment by Biswa96** [comment]
There has been an issue reported in upstream mingw-w64 mailing list here https://sourceforge.net/p/mingw-w64/mailman/message/37381669/. If author's views are correct this C++ thing may need a lot of changes.

Also a fix proposed in mingw-w64 mailing list here https://sourceforge.net/p/mingw-w64/mailman/message/37383240/. But that fix has to go first in wine because those winrt IDL files are imported from wine to mingw-w64. I can discuss this in IRC but first @jacekcw is familiar with both aisle.

**Comment by Biswa96** [comment]
Just realized, this may also need a change in WIDL instead of IDL files.

**Comment by Biswa96** [comment]
@rbernon suggested a patch file for WIDL tool here https://github.com/rbernon/wine/compare/wip/upstream...wip/widl/v1.patch. Test time 🔧

**Comment by rbernon** [comment]
[patch.gz](https://github.com/msys2/MINGW-packages/files/7568905/patch.gz)
Attaching the patch instead as I'm probably going to rewrite these branches.

**Comment by Biswa96** [comment]
The issue no longer be reproduced. Feel free to reopen the issue if the problem persists.
