### PR TITLE
Vid.stab: Build for CLANG* environments

### PR DESCRIPTION
**Pull request by mmuetzel**
Also use it in ffmpeg in these environments.

### CODE REVIEW

File: mingw-w64-vid.stab/PKGBUILD [hunk 1]
```diff
@@ -30,8 +46,8 @@ prepare() {
 
 build() {
   cd "$srcdir"/${_realname}-${pkgver}
-  [[ -d "${srcdir}"/build-${CARCH}-static ]] && rm -rf "${srcdir}"/build-${CARCH}-static
-  mkdir -p "${srcdir}"/build-${CARCH}-static && cd "${srcdir}"/build-${CARCH}-static
+  [[ -d "${srcdir}"/build-${MSYSTEM}-static ]] && rm -rf "${srcdir}"/build-${MSYSTEM}-static
```
Comment (kmilos) [inline mingw-w64-vid.stab/PKGBUILD:49]: The "-shared" and "-static" labels for the build folders seem to be reversed wrt to the actual build options?

File: mingw-w64-vid.stab/0001-OpenMP.patch [hunk 2]
```diff
@@ -0,0 +1,12 @@
+--- vid.stab-1.1/CMakeLists.txt.orig	2022-05-18 14:19:15.852140900 +0200
++++ vid.stab-1.1/CMakeLists.txt	2022-05-18 14:23:00.314303600 +0200
+@@ -71,7 +71,8 @@
+ target_link_libraries(vidstab ${ORC_LIBRARIES})
+ endif()
+ if(USE_OMP)
+-target_link_libraries(vidstab gomp)
++find_package(OpenMP)
++target_link_libraries(vidstab OpenMP::OpenMP_CXX)
```
[the remark this answers is not in the document]
Comment (mmuetzel) [reply mingw-w64-vid.stab/0001-OpenMP.patch:9]: I was reading this: https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html
And this: https://cmake.org/cmake/help/latest/module/FindOpenMP.html

That gave me the impression that the macro only sets some variables. But is up to the user to actually apply them. Is this not the case?

**Comment by mmuetzel** [comment]
Re-based to current HEAD and squashed some of the commits.

**Comment by mmuetzel** [comment]
Compiling ffmpeg now fails with:
```
  In file included from C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/libavcodec/cabac_functions.h:47,
                   from C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/libavcodec/h264_cabac.c:36:
  In function 'get_cabac_inline_x86',
      inlined from 'get_cabac' at C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/libavcodec/cabac_functions.h:140:12,
      inlined from 'decode_cabac_mb_intra4x4_pred_mode' at C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/libavcodec/h264_cabac.c:1368:9,
      inlined from 'ff_h264_decode_mb_cabac' at C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/libavcodec/h264_cabac.c:2072:32:
  C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
    199 |     __asm__ volatile(
        |     ^~~~~~~
  C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
  C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
  C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
  make: *** [/C/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.2/ffbuild/common.mak:67: libavcodec/h264_cabac.o] Error 1
  make: *** Waiting for unfinished jobs....
```

I didn't see that error in the CI before. Maybe something new with GCC 12.1?

**Comment by mmuetzel** [comment]
I added a patch that de-activates the assembler code that doesn't compile on MINGW32 with GCC 12.1. In that case, the implementation falls back to C code which might be less efficient. But at least, it seems to be compiling with that change.
