### ISSUE TITLE
Please help getting Rust 1.40 working

### ISSUE THREAD

**Issue by allquixotic** [msys2/MINGW-packages#6080]
Hi, I've started working on Rust 1.40 support here: https://github.com/allquixotic/MINGW-packages/commit/be6ce44c4975d2c23f55088fae3803cb4e494987

A few notes:

- When _bootstrap=no, the bootstrap.py errors out very early on when rust-1.37 is already installed on the system, possibly due to this issue: https://github.com/rust-lang/rust/issues/63964 Certainly the symptom is the same.
 - When _bootstrap=yes, it gets pretty far into the build (it successfully compiles the `std` package and quite a bit of librustc's dependencies), but compiling the librustc_llvm crate fails with tons of linker errors like this one:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\rustcwpVt7F\librustc_llvm-1cacb7b977047aff.rlib(Z3Solver.cpp.obj):(.text$_ZNK4llvm7SMTExprltERKS0_[_ZNK4llvm7SMTExprltERKS0_]+0x9e): undefined reference to `Z3_get_ast_id'
          collect2.exe: error: ld returned 1 exit status
```

There are approximately 80 of these, mostly referring to different functions.

 - The GPG key appears to be invalid and I'm not sure how to get a correct one. So I grabbed the sha256sum based on my download but I don't know what to put in `validpgpkeys` to get it to work without passing `--skippgpcheck` to the package build command (`MINGW_INSTALLS=mingw64 makepkg-mingw -sLf --skippgpcheck`).

**Comment by allquixotic** [comment]
Looks like those linker errors are because we need to add a new dependency in makedepends:

`"${MINGW_PACKAGE_PREFIX}-z3"`

Currently building again after installing the package from the repo.

**Comment by mati865** [comment]
`_bootstrapping=no` error is expected. You can only build Rust version N with version N-1.
That means you have to get Rust 1.38 and then 1.39 before 1.40.
Z3 error is because MSYS2 LLVM is built with Z3 library and Rust is configured to use MSYS2 LLVM. I suppose `llvm-config` doesn't print z3 as required library.

**Comment by bendem** [comment]
Weird question but if 1.40 doesn't work, does 1.38 or 1.39? If so, can we maybe update at least to that until we get 1.40 working?

**Comment by mati865** [comment]
FWIW LLVM Z3 error could be possibly worked around using `--enable-llvm-link-shared`.

**Comment by bendem** [comment]
I'd like to reiterate, can we get 1.38 or 1.39 out while waiting for 1.40? They both stabilized some now widely used features that make it impossible for msys users to compile programs using them.

Case in point:

```rust
$ cargo install bat
    Updating crates.io index
  Installing bat v0.12.1
   Compiling jobserver v0.1.21
[...]
   Compiling backtrace v0.3.44
error[E0658]: use of unstable library feature 'ptr_cast'
   --> C:\Users\demarteaub\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\dbghelp.rs:110:74
    |
110 |                 RtlLookupFunctionEntry(addr, &mut base, ptr::null_mut()).cast()
    |                                                                          ^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/60602

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `backtrace`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bat v0.12.1`, intermediate artifacts can be found at `C:\msys64\tmp\cargo-installIqgtWS`

Caused by:
  build failed
```

**Comment by mati865** [comment]
@Alexpux what'd you prefer: bootstrapping using repository packages (building Rust 1.38 -> 1.39 -> 1.40 -> 1.41) or bootstrapping directly from upstream provided Rust 1.40?

**Comment by Alexpux** [comment]
@mati865 we have in PKGBUILD bootstrapping possibility. Usually I use bootstrapping because not possible build with our version. So no matter for me what method to use

**Comment by lazka** [comment]
See #6250

**Comment by mati865** [comment]
Rust 1.41.1 is available in the repo, we can close this issue.
