### ISSUE TITLE
Problem with libdav1d

### ISSUE THREAD

**Issue by Jamaika1** [msys2/MINGW-packages#29299]
I use 
mingw-w64-ucrt-x86_64-crt-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst 
mingw-w64-ucrt-x86_64-winstorecompat-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst 
mingw-w64-ucrt-x86_64-libwinpthread-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst "
mingw-w64-ucrt-x86_64-libiconv-1.19-1-any.pkg (1).tar.zst" "
mingw-w64-ucrt-x86_64-zlib-1.3.2-2-any.pkg (2).tar.zst" 
mingw-w64-ucrt-x86_64-winpthreads-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst 
mingw-w64-ucrt-x86_64-windows-default-manifest-6.4-4-any.pkg.tar.zst 
mingw-w64-ucrt-x86_64-headers-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst "
mingw-w64-ucrt-x86_64-binutils-2.46-2-any.pkg (1).tar.zst" 
mingw-w64-ucrt-x86_64-gcc-libs-16.1.0-1-any.pkg.tar.zst 
mingw-w64-ucrt-x86_64-gcc-16.1.0-1-any.pkg.tar.zst 
libdav1d works with gcc 15.2.0.
```
gcc.exe -std=gnu17 -static -g0 -O3 -D_FORTIFY_SOURCE=3 -march=x86-64-v3 -mtune=generic -mthreads -mavx2 -mbmi -mbmi2 -mlzcnt -mfma -mmovbe -mhle -Wcomment -Wformat -Wshift-negative-value -DWINVER=0xA00 -D_WIN32_WINNT=0xA00 -UWIN32_LEAN_AND_MEAN -U__STRICT_ANSI__ -U__USE_MINGW_ANSI_STDIO -DARCH_X86=1 -DARCH_X86_32=0 -DARCH_X86_64=1 -DHAVE_ASM=1 -DCONFIG_8BPC -DCONFIG_16BPC -DBITDEPTH=8 -DHAVE_ALIGNED_MALLOC=1 -c thread_task.c -o thread_task.o
thread_task.c: In function 'delayed_fg_task':
thread_task.c:499:51: error: passing argument 4 of 'dav1d_prep_grain_16bpc' from incompatible pointer type [-Wincompatible-pointer-types]
  499 |                                    ttd->delayed_fg.scaling_16bpc,
      |                                    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      |                                                   |
      |                                                   uint8_t (*)[4096] {aka unsigned char (*)[4096]}
In file included from C:/gcc1610/x86_64-w64-mingw32/include/src/cdef.h:34,
                 from C:/gcc1610/x86_64-w64-mingw32/include/src/internal.h:42,
                 from C:/gcc1610/x86_64-w64-mingw32/include/src/thread_task.h:33,
                 from thread_task.c:32:
C:/gcc1610/x86_64-w64-mingw32/include/src/fg_apply.h:49:13: note: expected 'uint8_t (*)[256]' {aka 'unsigned char (*)[256]'} but argument is of type 'uint8_t (*)[4096]' {aka 'unsigned char (*)[4096]'}
   49 |             array_decl(uint8_t, scaling, [3][SCALING_SIZE]),
      |             ^~~~~~~~~~
```

**Comment by lazka** [comment]
* You can report it to libdav1d
* You can `export CFLAGS="-Wno-incompatible-pointer-types"`

**Comment by Jamaika1** [comment]
You're right. It's not msys2's fault.
https://code.videolan.org/videolan/dav1d/-/commit/f995e1fbf9379027367a93aafd2b5711ba76f81e
