### PR TITLE
wxPython: rebuild

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
```
  ../../sip/cpp/sip_corewxCollapsiblePane.cpp:97:15: error: 'wxSize sipwxCollapsiblePane::DoGetBorderSize() const' marked 'override', but does not override
     97 |      ::wxSize DoGetBorderSize() const SIP_OVERRIDE;
        |               ^~~~~~~~~~~~~~~
  ../../sip/cpp/sip_corewxCollapsiblePane.cpp: In member function 'wxSize sipwxCollapsiblePane::DoGetBorderSize() const':
  ../../sip/cpp/sip_corewxCollapsiblePane.cpp:295:38: error: 'DoGetBorderSize' is not a member of 'wxGenericCollapsiblePane'
    295 |         return  ::wxCollapsiblePane::DoGetBorderSize();
        |                                      ^~~~~~~~~~~~~~~
  ../../sip/cpp/sip_corewxCollapsiblePane.cpp: In member function 'wxSize sipwxCollapsiblePane::sipProtectVirt_DoGetBorderSize(bool) const':
  ../../sip/cpp/sip_corewxCollapsiblePane.cpp:869:51: error: 'DoGetBorderSize' is not a member of 'wxGenericCollapsiblePane'
    869 |     return (sipSelfWasArg ?  ::wxCollapsiblePane::DoGetBorderSize() : DoGetBorderSize());
        |                                                   ^~~~~~~~~~~~~~~
```

this looks related to https://github.com/wxWidgets/wxWidgets/pull/2445

@stahta01 do you know how to fix this?

**Comment by stahta01** [comment]
wxPython needs to be built with a close match of wxWidgets; It is broken as a stated by the wxWidgets 2.1.6 upgrade.

Tim S.

**Comment by stahta01** [comment]
If you just wish to rebuild with wxWidgets 3.1.6 use my PR #11811

Note: That change does not work with wxWidgets 3.1.7

Tim S.

**Comment by lazka** [comment]
closing since #11835 is merged now.
