### PR TITLE
Update OpenCV to 4.5.5 release - fixes import cv2

### PR DESCRIPTION
**Pull request by ugur-kurnaz**
updated opencv to release 4.5.5.
patches for mingw have just been adapted to new version of opencv, without further analysis if adaptation (WIN32=>MINGW) is needed elsewhere.
some patches seems to be included in new release of 4.5.5 (applied without verbosing anything nor complaining of failure).

this update has fixed 'import cv2' in python scripts not working with previous version (4.5.2). I didn't use much opencv and opencv_python functionalities, so only basic tests have been done in both C++ and python.

### CODE REVIEW

**Comment by ugur-kurnaz** [comment]
seems that mingw-w64-clang-x86_64-vtk is missing for clang64 arch.

but even when commenting out this dep, build still fails in this arch due to a problem of float casting in eigen3

```
In file included from E:/projets/MINGW-packages/mingw-w64-opencv/src/build-x86_64/modules/core/matmul.avx512_skx.cpp:2:
In file included from E:/projets/MINGW-packages/mingw-w64-opencv/src/opencv-4.5.5/modules/core/src/precomp.hpp:59:
In file included from E:/projets/MINGW-packages/mingw-w64-opencv/src/opencv-4.5.5/modules/core/include/opencv2/core/private.hpp:70:
In file included from C:/msys64/clang64/include/eigen3/Eigen/Core:188:
C:/msys64/clang64/include/eigen3/Eigen/src/Core/arch/AVX512/PacketMath.h:1044:10: error: cannot initialize return object of type 'float' with an rvalue of type 'typename unpacket_traits<__attribute__((__vector_size__(4 * sizeof(float)))) float>::type' (aka '__attribute__((__vector_size__(4 * sizeof(float)))) float')
  return pfirst(pmul(res, _mm_permute_ps(res, _MM_SHUFFLE(0, 0, 0, 1))));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/clang64/include/eigen3/Eigen/src/Core/arch/AVX512/PacketMath.h:1064:10: error: cannot initialize return object of type 'float' with an rvalue of type 'typename unpacket_traits<__attribute__((__vector_size__(4 * sizeof(float)))) float>::type' (aka '__attribute__((__vector_size__(4 * sizeof(float)))) float')
  return pfirst(_mm_min_ps(res, _mm_permute_ps(res, _MM_SHUFFLE(0, 0, 0, 1))));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/clang64/include/eigen3/Eigen/src/Core/arch/AVX512/PacketMath.h:1083:10: error: cannot initialize return object of type 'float' with an rvalue of type 'typename unpacket_traits<__attribute__((__vector_size__(4 * sizeof(float)))) float>::type' (aka '__attribute__((__vector_size__(4 * sizeof(float)))) float')
  return pfirst(_mm_max_ps(res, _mm_permute_ps(res, _MM_SHUFFLE(0, 0, 0, 1))));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:1573 : modules/core/CMakeFiles/opencv_core.dir/matmul.avx512_skx.cpp.obj] Erreur 1
make[2]: *** Attente des tâches non terminées....
make[1]: *** [CMakeFiles/Makefile2:3316 : modules/core/CMakeFiles/opencv_core.dir/all] Erreur 2
make: *** [Makefile:166 : all] Erreur 2
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…
```

**Comment by kmilos** [comment]
Would also need to bump and rebuild all the depending packages as well due to *452.dll->*455.dll name change.

**Comment by ugur-kurnaz** [comment]
closing, because I've merged patch files into one, and this isn't a good practice.  History of changes and patches are somehow lost.
I've also analysed a bit the deps and build config, and there are some flaws :
- freetype and harfbuzz are mutually dependent
- freetype and harfbuzz are not detected
- gstreamer is not detected
- gphoto2 neither
- opencv and vtk are mutually dependent
- ffmpeg depends on frei0r-plugin that depend on opencv, should not be put as opencv dep (opencv build automatically downloads a pre built version, that should be prefered)
- when building with MSMF (-lmf -ldxva2), I think adapted headers from mingw are not used. 


concerning the detection issues, it just happen that pkg-config is not used. I've managed to force it by appending "find_package(PkgConfig) " to the root CmakeList.txt (just at the first line not knowing where to put it else), it solves some of the issues.

for gstreamer, in module/videoio/cmake/detect_gstreamer.cmake, one also need to move the block for pkg_config_found before the block for WIN32. thus all sub-modules are correctly detected.

the main issue, remaining an error in clang64 architecture.
