### PR TITLE
enable go packages for clang32 and clangarm64

### PR DESCRIPTION
**Pull request by jeremyd2019**
Except for dnslookup, which fails with
```
C:\Users\runneradmin\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.24.0\internal\qtls\go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
```

and butler, which never successfully built on CLANG64.

Also, it appears that go packages now makedepend on `git`.  There was a reference to an option in the error that may be able to disable that, but it wasn't clear where that option would go (GOFLAGS? arg to `go build` on package that builds that way?)
```
  go: missing Git command. See https://golang.org/s/gogetcmd
  error obtaining VCS status: exec: "git": executable file not found in %PATH%
  	Use -buildvcs=false to disable VCS stamping.
```

### CODE REVIEW

**Comment by jeremyd2019** [comment]
```
 # golang.org/x/sys/windows
  vendor\golang.org\x\sys\windows\zsyscall_windows.go:2402:38: undefined: WSAData
  vendor\golang.org\x\sys\windows\zsyscall_windows.go:2642:51: undefined: Servent
  vendor\golang.org\x\sys\windows\zsyscall_windows.go:2656:50: undefined: Servent
  vendor\golang.org\x\sys\windows\zsyscall_windows.go:2658:8: undefined: Servent
  make: *** [Makefile:52: bin/hub] Error 2
```

**Comment by jeremyd2019** [comment]
```
  # github.com/gohugoio/hugo
  loadinternal: cannot find runtime/cgo
  .debug_frame+1MB: addpesym: could not map .debug_frame+1MB symbol with non .text or .rdata or .data section
  .debug_frame+2MB: addpesym: could not map .debug_frame+2MB symbol with non .text or .rdata or .data section
``

**Comment by jeremyd2019** [comment]
I *think* `loadinternal: cannot find runtime/cgo` is it's not-so-clear way of saying that the C compiler and headers are not found.

**Comment by jeremyd2019** [comment]
That doesn't really track though, because hugo makedepends on `${MINGW_PACKAGE_PREFIX}-cc`.  Probably have to try investigating this more.

**Comment by jeremyd2019** [comment]
slightly more context:
```
GOROOT_FINAL='go' "C:\\msys64\\clangarm64\\lib\\go\\pkg\\tool\\windows_arm64\\link.exe" -o "$WORK\\b001\\exe\\a.out.exe" -importcfg "$WORK\\b001\\importcfg.link" -buildmode=exe -buildid=zTpodkfHHIWSFAshvte9/dM21tHXSw9fm96VWjBWM/w0O52mYE-ORx31Itg7gZ/zTpodkfHHIWSFAshvte9 -linkmode=external -extld=clang "C:\\Users\\Administrator\\AppData\\Local\\go-build\\b8\\b8c82c3b997bbedc0579a9f5aab58cd658be3d9371e982d155361869804ab850-d"
# github.com/gohugoio/hugo
loadinternal: cannot find runtime/cgo
.debug_frame+1MB: addpesym: could not map .debug_frame+1MB symbol with non .text or .rdata or .data section
.debug_frame+2MB: addpesym: could not map .debug_frame+2MB symbol with non .text or .rdata or .data section
```

The message seems to come from go though, not using clang as an external linker.  But, taking away the linkmode=external option makes that error go away:
```
GOROOT_FINAL='go' "C:\\msys64\\clangarm64\\lib\\go\\pkg\\tool\\windows_arm64\\link.exe" -o "$WORK\\b001\\exe\\a.out.exe" -importcfg "$WORK\\b001\\importcfg.link" -buildmode=pie -buildid=R-5AlZiob4lGP_A0Xazo/qhFb3jH47ZtFgBLI_oak/w0O52mYE-ORx31Itg7gZ/R-5AlZiob4lGP_A0Xazo -extld=clang "$WORK\\b001\\_pkg_.a"
```

Anyone know why `-ldflags=-linkmode=external` is used?  @ifurther ?

**Comment by jeremyd2019** [comment]
Apparently it's part of Arch's [Go package guidelines](https://wiki.archlinux.org/title/Go_package_guidelines)

**Comment by jeremyd2019** [comment]
What's interesting is that the addpesym error only shows up when using `-ldflags=-linkmode=external`, but it seems to be a message coming from go's internal linker:
https://github.com/golang/go/blob/4aa1efed4853ea067d665a952eee77c52faac774/src/cmd/link/internal/ld/pe.go#L690

**Comment by jeremyd2019** [comment]
https://github.com/golang/go/issues/51903 for the addpesym error
