### ISSUE TITLE
binutils >=2.39 bfd library is broken for 32-bit

### ISSUE THREAD

**Issue by orgads** [msys2/MINGW-packages#15789]
### Description / Steps to reproduce the issue

main.c:
```c
#define PACKAGE "bfd"
#define HAVE_INTTYPES_H 1
#include <windows.h>
#include <bfd.h>

int main()
{
    char procname[MAX_PATH];
    bfd *bfd_;
    GetModuleFileNameA(NULL, procname, sizeof(procname));

    bfd_init();
    bfd_ = bfd_openr(procname, 0);
    if (!bfd_)
        return 1;
    bfd_close(bfd_);
    return 0;
}
```

```sh
$ g++ main.c -lbfd -liberty -lintl -lzstd -lz # on 2.40, add also -lsframe
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../lib/libbfd.a(opncls.o):(.text+0x1c8): undefined reference to `__stack_chk_guard'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../lib/libbfd.a(opncls.o):(.text+0x26d): undefined reference to `__stack_chk_guard'
...
```

Works fine with 64-bit, and with 2.38.

I tried passing `-fstack-protector-all` and other variants, and also `-lssp`. Nothing helps.

### Expected behavior

It should link.

### Actual behavior

It fails as I showed above.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-19043

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

If someone guides me, I can try to debug and submit a PR.

**Comment by revelator** [comment]
ssp is part of the mingw-w64-abi runtimes now i think.
still this sounds like a bug and there was mention of some function which was missed in portage by mstorsjoe getting added to the next update of the mingw-w64 abi so this might be it.

**Comment by orgads** [comment]
CC @mstorsjo

**Comment by mstorsjo** [comment]
> there was mention of some function which was missed in portage by mstorsjoe getting added to the next update of the mingw-w64 abi so this might be it.

No, this isn't it - `__stack_chk_guard` was part of the libmingwex.a bundled SSP symbols from the very beginning.

@orgads I tried reproducing this, but I failed - both in a local installation, and on a test job on github actions, setting things up from scratch (just installing `mingw-w64-i686-toolchain`, grabbing the file and running the quoted command).

**Comment by orgads** [comment]
Very strange. I also get it when trying to build gdb, on libexpat detection. I'll try to reinstall some packages and report back.

**Comment by orgads** [comment]
A clean installation of msys works, but on my existing installation, even after reinstalling all the related packages, it still doesn't work.

Any suggestions how to debug this?

**Comment by revelator** [comment]
was refering to _gets_chk from this thread ->

```
When a subset of ssp functions were implemented in
7478c20848f60e6238547db63d1a5bc450d468cc, only functions that were
referenced with _FORTIFY_SOURCE were added. This set of functions
accidentally missed __gets_chk, which we do reference if fortification
is enabled.

Thus, this fixes an accidental omission.
```

but yeah would be pretty strange if this is what causes it.

**Comment by mstorsjo** [comment]
> A clean installation of msys works, but on my existing installation, even after reinstalling all the related packages, it still doesn't work.
> 
> Any suggestions how to debug this?

Since `libmingwex.a` now provides the relevant symbols, msys2 provides empty placeholders for `libssp.a` and `libssp_nonshared.a`. But it seems like it's using a different/outdated `libmingwex.a` in your case, which doesn't provide it.

I presume `nm /mingw32/lib/libmingwex.a | grep stack_chk` shows that the symbols are found. You can try to add `-Wl,-verbose` to the linking command and see where it actually does pick up `libmingwex.a`.

**Comment by revelator** [comment]
guess it should look like this then 

```
lib32_libmingwex_a-stack_chk_fail.o:
00000000 T ___stack_chk_fail
lib32_libmingwex_a-stack_chk_guard.o:
00000000 B ___stack_chk_guard
```
my bad

**Comment by orgads** [comment]
Ok, I have 2 files:
```
/mingw32/lib/libmingwex.a - good
/mingw32/i686-w64-mingw32/lib/libmingwex.a - bad
```
and the second one is picked by the linker. Maybe it remained from older versions of the package?

**Comment by mstorsjo** [comment]
> Ok, I have 2 files:
> 
> ```
> /mingw32/lib/libmingwex.a - good
> /mingw32/i686-w64-mingw32/lib/libmingwex.a - bad
> ```
> 
> and the second one is picked by the linker. Maybe it remained from older versions of the package?

Yes, that seems probable.
