### ISSUE TITLE
Problem with glslang vulkan

### ISSUE THREAD

**Issue by Jamaika1** [msys2/MINGW-packages#29301]
I use
mingw-w64-ucrt-x86_64-crt-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst
mingw-w64-ucrt-x86_64-winstorecompat-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst
mingw-w64-ucrt-x86_64-libwinpthread-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst "
mingw-w64-ucrt-x86_64-libiconv-1.19-1-any.pkg (1).tar.zst" "
mingw-w64-ucrt-x86_64-zlib-1.3.2-2-any.pkg (2).tar.zst"
mingw-w64-ucrt-x86_64-winpthreads-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst
mingw-w64-ucrt-x86_64-windows-default-manifest-6.4-4-any.pkg.tar.zst
mingw-w64-ucrt-x86_64-headers-14.0.0.r14.g4761eabdd-1-any.pkg.tar.zst "
mingw-w64-ucrt-x86_64-binutils-2.46-2-any.pkg (1).tar.zst"
mingw-w64-ucrt-x86_64-gcc-libs-16.1.0-1-any.pkg.tar.zst
mingw-w64-ucrt-x86_64-gcc-16.1.0-1-any.pkg.tar.zst
glslang works with gcc 15.2.0.
```
GlslangToSpv.cpp: In member function 'virtual bool {anonymous}::TGlslangToSpvTraverser::visitAggregate(glslang::TVisit, glslang::TIntermAggregate*)':
GlslangToSpv.cpp:4010:35: error: 'EOpAbortEXT' is not a member of 'glslang'
 4010 |     if (node->getOp() == glslang::EOpAbortEXT) {
      |                                   ^~~~~~~~~~~
```
