### ISSUE TITLE
mingw-w64-qt-creator breaking CI on SIS_NEVER

### ISSUE THREAD

**Issue by jayvdb** [msys2/MINGW-packages#5861]
https://ci.appveyor.com/project/Alexpux/mingw-packages/builds/28041853/job/oy4o2vn3xstwkvym

```console
g++  -o release/moc_perforceversioncontrol.o release/moc_perforceversioncontrol.cpp
C:/M/mingw-w64-qt-creator/src/qt-creator-opensource-src-4.10.1/src/plugins/clangformat/clangformatutils.cpp: In function 'clang::format::FormatStyle ClangFormat::qtcStyle()':
C:/M/mingw-w64-qt-creator/src/qt-creator-opensource-src-4.10.1/src/plugins/clangformat/clangformatutils.cpp:63:62: error: 'SIS_Never' is not a member of 'clang::format::FormatStyle'
   63 |     style.AllowShortIfStatementsOnASingleLine = FormatStyle::SIS_Never;
      |                                                              ^~~~~~~~~
```

However without [the patch](https://github.com/msys2/MINGW-packages/blob/39395394f6869636ec568872f88974fde38cc827/mingw-w64-qt-creator/qt-creator-4.10.1-clang-9.patch) which uses SIS_Never:

```console
C:/M/mingw-w64-qt-creator/src/qt-creator-opensource-src-4.10.1/src/plugins/clangformat/clangformatutils.cpp:63:49: error: cannot convert 'bool' to 'clang::format::FormatStyle::ShortIfStyle' in assignment
   63 |     style.AllowShortIfStatementsOnASingleLine = false;
      |                                                 ^~~~~
```

So an acceptable value is needed.  Need to dig up which `clang::format::FormatStyle` it is being compiled against and find an appropriate value.

**Comment by Alexpux** [comment]
@jayvdb CI use clang/llvm 8.0.1 while Im build with 9.0.0

**Comment by jayvdb** [comment]
Hiya @Alexpux , I am new here, what does "lm" refer to?

**Comment by mingwandroid** [comment]
Im == I am.

**Comment by jayvdb** [comment]
ok, does that mean we need the patch to work for both 8.0.1 and 9.0.0?

**Comment by mingwandroid** [comment]
Well, I suppose the CI could be updated, not sure who'd do that.

You can work on the recipe and test builds locally. MSYS2 makes that very easy.

**Comment by MehdiChinoune** [comment]
closing since the package has been updated
